### ISSUE TITLE
Passing custom llm in Functions is not supported/working

### ISSUE THREAD

**Issue by ankush-ksharma** [simbianai/taskgen#2]
In  class Function: when a custom llm is passed, this kwargs is not passed properly into "strict_json" call. Please check,

**Comment by tanchongmin** [comment]
will look into it, thanks for pointing out

**Comment by tanchongmin** [comment]
@ankush-ksharma 
v1.1.0 should have very robust checks to ensure that the llm is passed all the way from Agent to Function to strict_json
I have specified the llm variable as inputs for each of these classes/functions
