### ISSUE TITLE
Prompting fails on Phi3

### ISSUE THREAD

**Issue by richard087** [simbianai/taskgen#7]
While it's very reasonable to rule out support for some LLMs, I tested on Phi3 and found that it doesn't generate any output.

My example notebook is at https://gist.github.com/richard087/8e5d5ec4442da4dd4bdeec2a69c72caf

**Comment by tanchongmin** [comment]
Can try again? v2.1.1 has been rejigged for most LLMs already by specifying starting with { and ending with } to force JSON output

**Comment by richard087** [comment]
Same result, I'm afraid.
```
def llm(system_prompt: str, user_prompt: str):
    messages = [{"role": "system", "content": system_prompt}, {"role": "user", "content": user_prompt}]
    output = pipe(messages, **generation_args)
    res = output[0]['generated_text']
    return res

res = strict_json(system_prompt = 'You are a classifier',
                    user_prompt = 'It is a beautiful and sunny day',
                    output_format = {'Sentiment': 'Type of Sentiment',
                                    'Adjectives': 'Array of adjectives',
                                    'Words': 'Number of words'},
                    debug=True,
                    llm = llm) # set this to your own LLM
print(res)
```
Gives output:
'''
An exception occurred: string index out of range
Current invalid json format: 
An exception occurred: string index out of range
Current invalid json format: 
An exception occurred: string index out of range
Current invalid json format: 
{}
```

**Comment by tanchongmin** [comment]
Kindly check again for TaskGen v3.1.0 and see if it still fails.

I have added in more robust JSON error handling and prompting for the JSON.

**Comment by richard087** [comment]
using taskgen-ai v3.2.0 gives proper response.
``` 
{'Sentiment': 'Positive', 'Adjectives': ['beautiful', 'sunny'], 'Words': 6}
```
